name: build and push cloud run containers

on:
  workflow_call:
    outputs:
      sha:
        value: ${{ jobs.push.outputs.build_tag }}
    inputs:
      GAR_LOCATION:
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
      RUN_SERVICE_NAME:
        required: true
        type: string
      RUN_SERVICE_REGION:
        required: true
        type: string
    secrets:
      WIF_PROVIDER:
        required: true
      WIF_SERVICE_ACCOUNT:
        required: true
      PROJECT_ID:
        required: true
          

jobs:
  push:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    
    outputs:
      build_tag: ${{ steps.push.outputs.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3.0.0'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ inputs.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build Image
        id: build
        run: |-
          cd ./code/services/home_page
          docker build -t "${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ inputs.REPOSITORY_NAME }}/${{ inputs.RUN_SERVICE_NAME }}:${{ github.sha }}" ./

      - name: Push Image
        id: push
        run: |-
          cd ./code/services/home_page
          echo "sha=${{github.sha}}" >> $GITHUB_OUTPUT
          docker push "${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ inputs.REPOSITORY_NAME }}/${{ inputs.RUN_SERVICE_NAME }}:${{ github.sha }}"
